name: Dronespot
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f4049'
    - '#041424'
    - '#9e7150'
    - '#f2ec8c'
    - '#ecc270'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
