name: Dronespot
favicon: null
layout_spectrum: 0.47541991085745394
typography_spectrum: 0.023711168905720115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e84bc'
    - '#0000ff'
    - '#00ffff'
    - '#000000'
    - '#0055aa'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
