name: Dronespot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e84bc'
    - '#0055aa'
    - '#0000ff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
